In [1]:
import pandas as pd
#load datasets

# List of dataset files
files = ['movies.csv', 'links.csv', 'ratings.csv', 'tags.csv']

# Dictionary to store DataFrames
dfs = {}

# Load each dataset and store it in the dictionary
for file in files:
    df_name = file.split('.')[0]  # Extract DataFrame name from the file name
    dfs[df_name] = pd.read_csv(file)

# Display information about each DataFrame
for df_name, df in dfs.items():
    print(f"\nInfo for {df_name}:")
    print(df.info())

    # print the first few rows of the DataFrame
    print(f"\nFirst few rows of {df_name}:")
    print(df.head())

Info for movies:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB
None

First few rows of movies:
   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

Info for links:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB
None

First few rows of links:
   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

Info for ratings:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB
None

First few rows of ratings:
   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

Info for tags:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     3683 non-null   int64
 1   movieId    3683 non-null   int64
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB
None

First few rows of tags:
   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [2]:
# Merging datasets using movieId as the key
merged_df = pd.merge(dfs['movies'], dfs['links'], on='movieId', how='left')
merged_df = pd.merge(merged_df, dfs['ratings'], on='movieId', how='left')
merged_df = pd.merge(merged_df, dfs['tags'], on='movieId', how='left')

# Display information about the merged DataFrame
print("\nInfo for merged DataFrame:")
print(merged_df.info())

# Display summary statistics for the merged DataFrame
print("\nSummary statistics for merged DataFrame:")
print(merged_df.describe())

Info for merged DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285783 entries, 0 to 285782
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   movieId      285783 non-null  int64
 1   title        285783 non-null  object
 2   genres       285783 non-null  object
 3   imdbId       285783 non-null  int64
 4   tmdbId       285770 non-null  float64
 5   userId_x     285762 non-null  float64
 6   rating       285762 non-null  float64
 7   timestamp_x  285762 non-null  float64
 8   userId_y     233234 non-null  float64
 9   tag          233234 non-null  object
 10  timestamp_y  233234 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 24.0+ MB
None

Summary statistics for merged DataFrame:
             movieId        imdbId         tmdbId       userId_x  \
count  285783.000000  2.857830e+05  285770.000000  285762.000000
mean    14927.663741  2.956050e+05   12797.315320     313.894279
std     31402.673519  5.150156e+05   43479.255523     179.451387
min         1.000000  4.170000e+02       2.000000       1.000000
25%       296.000000  1.098300e+05     489.000000     160.000000
50%      1721.000000  1.125730e+05     680.000000     314.000000
75%      5673.000000  2.415270e+05    8963.000000     465.000000
max    193609.000000  8.391976e+06  525662.000000     610.000000

              rating   timestamp_x       userId_y   timestamp_y
count  285762.000000  2.857620e+05  233234.000000  2.332340e+05
mean        3.841270  1.214707e+09     470.681354  1.384754e+09
std         1.020798  2.233730e+08     153.324249  1.534705e+08
min         0.500000  8.281246e+08       2.000000  1.137179e+09
25%         3.000000  1.019133e+09     424.000000  1.242494e+09
50%         4.000000  1.211377e+09     477.000000  1.457901e+09
75%         4.500000  1.445346e+09     599.000000  1.498457e+09
max         5.000000  1.537799e+09     610.000000  1.537099e+09

In [3]:
# Display summary statistics for the merged DataFrame
print("\nSummary statistics for merged DataFrame:")
print(merged_df.describe())

Summary statistics for merged DataFrame:
             movieId        imdbId         tmdbId       userId_x  \
count  285783.000000  2.857830e+05  285770.000000  285762.000000
mean    14927.663741  2.956050e+05   12797.315320     313.894279
std     31402.673519  5.150156e+05   43479.255523     179.451387
min         1.000000  4.170000e+02       2.000000       1.000000
25%       296.000000  1.098300e+05     489.000000     160.000000
50%      1721.000000  1.125730e+05     680.000000     314.000000
75%      5673.000000  2.415270e+05    8963.000000     465.000000
max    193609.000000  8.391976e+06  525662.000000     610.000000

              rating   timestamp_x       userId_y   timestamp_y
count  285762.000000  2.857620e+05  233234.000000  2.332340e+05
mean        3.841270  1.214707e+09     470.681354  1.384754e+09
std         1.020798  2.233730e+08     153.324249  1.534705e+08
min         0.500000  8.281246e+08       2.000000  1.137179e+09
25%         3.000000  1.019133e+09     424.000000  1.242494e+09
50%         4.000000  1.211377e+09     477.000000  1.457901e+09
75%         4.500000  1.445346e+09     599.000000  1.498457e+09
max         5.000000  1.537799e+09     610.000000  1.537099e+09